### ISSUE TITLE
Deleting blocks

### ISSUE THREAD

**Issue by ghost** [ElementalCode/ElementalCode.github.io#5]
There's a problem when i tried to delete blocks. sometimes it doesn't disappear.

**Comment by ghost** [comment]
Hello?

**Comment by matthewr6** [comment]
It's me...

**Comment by PullJosh** [comment]
Looks like it's time to make **a dele**te function.

Not even sorry.

**Comment by matthewr6** [comment]
want to do that, @PullJosh?  :P

**Comment by PullJosh** [comment]
No. I just wanted to make that pun.

**Comment by matthewr6** [comment]
Oh.

**Comment by matthewr6** [comment]
So who still does things?

**Comment by ghost** [comment]
Idk, i noticed that this repo is inactive
